version: '3'

services:
  four-ti-db:
    image: postgres
    container_name: four-ti-db
    restart: unless-stopped
    # set shared memory limit when using docker-compose
    shm_size: 128mb
    # or set shared memory limit when deploy via swarm stack
    networks:
      - four-ti
    volumes:
      - dbdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=$DATABASE_PASSWORD
      - POSTGRES_USER=$DATABASE_USER
      - POSTGRES_DB=$DATABASE_NAME
    ports:
      - 54320:5432
  four-ti:
    build:
      context: .
      dockerfile: Dockerfile
    image: four-ti-backend/four-ti
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    container_name: four-ti
    tty: true
    restart: unless-stopped
    env_file: .env
    environment:
      - DATABASE_HOST=four-ti-db
      - DATABASE_URL=postgres://${DATABASE_USER}:${DATABASE_PASSWORD}@four-ti-db:5432/${DATABASE_NAME}
    ports:
      - '${PORT}:${PORT}'
    volumes:
      - .:/home/node/app
      - node_modules:/home/node/app/node_modules
    networks:
      - four-ti

networks:
  four-ti:
    driver: bridge
    external: false

volumes:
  dbdata:
  node_modules:
